on: [push]
name: Exporting variables by overwriting
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Export environment type
        uses: kanga333/variable-mapper@v0.3.0
        with:
          key: "${{ steps.extract_env.outputs.branch }}"
          map: |
            {
              "main": {
                "environment": "prod"
              },
              "release": {
                "environment": "stg"
              },
              "develop": {
                "environment": "dev"
              },
              "sandbox1":{
                "environment": "sandbox1"
              },
              "sandbox2":{
                "environment": "sandbox2"
              },
              ".*": {
                "environment": "unmapped"
              }
            }
      - name: Echo environment and output
        run: |
          echo ${{ env.environment }}
