on: [push]
name: Exporting variables by overwriting
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract env name
        shell: bash
        id: extract_env
        run: |
          branch=${GITHUB_REF#refs/heads/}
          name=${branch%%/*}
          echo "BRANCH=$(echo ${branch%%/*})" >> $GITHUB_OUTPUT
          echo "FULL_BRANCH=$(echo ${branch})" >> $GITHUB_OUTPUT
      - name: Echo branch
        run : |
          echo ${{steps.extract_env.outputs.branch}}
      - name: Export environment type
        uses: kanga333/variable-mapper@v0.3.0
        with:
          key: "${{ steps.extract_env.outputs.branch }}"
          map: |
            {
              "main": {
                "environment": "prod"
              },
              "release": {
                "environment": "stg"
              },
              "develop": {
                "environment": "dev"
              },
              "sandbox1":{
                "environment": "sandbox1"
              },
              "sandbox2":{
                "environment": "sandbox2"
              },
              ".*": {
                "environment": "unmapped"
              }
            }
      - name: Echo environment and output
        run: |
          echo ${{ env.environment }}
      - name: test extend
        uses: ./.github/test-extend
        with:
          environment: ${{env.environment}}
